serve-path: /data
bind: 0.0.0.0
port: 5000
allow-all: false
allow-upload: false
allow-delete: false
allow-search: false
allow-symlink: false
allow-archive: false
allow-hash: false
log-file: /logs/dufs.log
